[package]
name = "hapvol"
version = "0.1.0"
authors = ["Lukas Dötlinger <lukas.doetlinger@student.uibk.ac.at>"]
edition = "2018"

[dependencies]
serialport = "3.3.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["endpointvolume", "objbase", "mmdeviceapi"] }
