[package]
name = "hapvol"
version = "0.1.0"
authors = ["Lukas Dötlinger <lukas.doetlinger@student.uibk.ac.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
